CREATE TABLE IF NOT EXISTS products (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    protein     DOUBLE PRECISION,
    fat         DOUBLE PRECISION,
    carbs       DOUBLE PRECISION,
    image_key   VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS meals (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(255) NOT NULL,
    year        INTEGER,
    month       INTEGER,
    day         INTEGER,
    meal_time   TIME
);

CREATE TABLE IF NOT EXISTS meal_products (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    meal_id     INTEGER NOT NULL,
    product_id  INTEGER NOT NULL,
    grams       DOUBLE PRECISION,
    calories    DOUBLE PRECISION,

    CONSTRAINT fk_meal
        FOREIGN KEY (meal_id)
        REFERENCES meals(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_product
        FOREIGN KEY (product_id)
        REFERENCES products(id)
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_meal_products_meal_id
    ON meal_products(meal_id);

CREATE INDEX IF NOT EXISTS idx_meal_products_product_id
    ON meal_products(product_id);
